config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  resources :projects do
    member do
      post :invite # Route for inviting users
      get :accept_invite # Route for accepting invitations
    end
    resources :tasks
    resources :faqs
  end
  root "application#home"
  resources :notifications do
    member do
      post 'read'  # This creates a POST route for marking notifications as read
    end
  end
end

app/models/faq.rb
class Faq < ApplicationRecord
  belongs_to :project
  after_save :create_notification
  validates :question, presence: true
  validates :answer, presence: true

  private

  def create_notification
    self.project.users.each do |user|
      FaqCreatedNotifier.with(faq: self, project: self.project).deliver_later(user)
    end
  end
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_faq, only: %i[show edit update destroy]

  def index
    @faqs = @project.faqs
  end

  def show; end

  def new
    @faq = @project.faqs.build
  end

  def create
    @faq = @project.faqs.build(faq_params)
    respond_to do |format|
      if @faq.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    if @faq.update(faq_params)
      redirect_to project_faq_path(@project, @faq), notice: 'FAQ was successfully updated.'
    else
      render :edit, alert: 'Failed to update FAQ.'
    end
  end

  def destroy
    @faq.destroy
    redirect_to project_faqs_path(@project), notice: 'FAQ was successfully destroyed.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_faq
    @faq = @project.faqs.find(params[:id])
  end

  def faq_params
    params.require(:faq).permit(:question, :answer)
  end
end

app/views/faqs/_faq.html.erb
<li class="flex justify-between items-center p-4 bg-white shadow-md rounded-lg">
  <div class="flex-1">
    <p class="font-bold truncate">
      <%= link_to truncate(faq.question, length: 30), project_faq_path(@project, faq), class: "text-blue-500 hover:text-blue-700" %>
    </p>
    <p class="text-gray-600 truncate">
      <%= truncate(faq.answer, length: 40) %>
    </p>
  </div>
  <div class="space-x-2">
    <%= link_to 'Edit', edit_project_faq_path(@project, faq), class: "text-blue-500 hover:text-blue-700" %>
    <%= link_to 'Delete', project_faq_path(@project, faq), data: { "turbo-method": :delete }, class: "text-red-500 hover:text-red-700" %>
  </div>
</li>

app/views/faqs/_form.html.erb
<%= turbo_frame_tag id='faq_form', target: '_top' do %>
  <%= form_with(model: [project, faq], local: true) do |f| %>
    <div class="max-w-md mx-auto mb-4">
      <%= f.label :question, "Question", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :question, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="max-w-md mx-auto mb-4">
      <%= f.label :answer, "Answer", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :answer, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="flex justify-center items-center mt-6 space-x-4">
      <%= f.submit "Create FAQ", class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
<% end %>

app/views/faqs/create.turbo_stream.erb
<%= turbo_stream.append "faqs", @faq %>
<%= turbo_stream.replace 'faq_form', partial: 'form', locals: {project: @project, faq: Faq.new} %>

app/views/faqs/edit.html.erb
<h1 class="text-3xl font-bold mb-4 text-center">Edit FAQ</h1>
<div class="flex justify-center space-x-4 mb-4">
  <%= link_to 'Back to FAQs', project_faqs_path(@project), class: "bg-gray-500 text-white py-2 px-4 rounded transition duration-200 hover:bg-gray-600" %>
</div>

<div class="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <%= turbo_frame_tag id='faq_form' do %>
    <%= render 'form', faq: @faq, project: @project%>
  <% end %>
</div>

app/views/faqs/index.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">FAQs</h1>

<div class="flex justify-center space-x-4 mb-4">
  <%= link_to 'Back to Project', project_path(@project), class: "bg-gray-500 text-white py-2 px-4 rounded transition duration-200 hover:bg-gray-600" %>
</div>
<%= turbo_frame_tag id='faq_form', src:new_project_faq_path(@project) %>
<ul class="space-y-4 mb-4" id="faqs">
  <% @faqs.each do |faq| %>
    <%= render 'faq', faq: faq %>
  <% end %>
</ul>

app/views/faqs/new.html.erb
<h1 class="text-3xl font-bold text-center mb-4">New FAQ</h1>

<%= turbo_frame_tag id='faq_form' do %>
  <%= render 'form', faq: @faq, project: @project%>
<% end %>

app/views/faqs/show.html.erb
<h1 class="text-3xl font-bold text-center mb-4">FAQ Details</h1>

<div class="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <div class="mb-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-2">Question:</h2>
    <p class="text-gray-700"><%= @faq.question %></p>
  </div>

  <div class="mb-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-2">Answer:</h2>
    <p class="text-gray-700"><%= @faq.answer %></p>
  </div>

  <div class="flex justify-between items-center mt-6">
    <div class="flex space-x-4">
      <%= link_to 'Edit', edit_project_faq_path(@project, @faq), class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-200" %>
      <%= link_to 'Delete', project_faq_path(@project, @faq), data: { "turbo-method": :delete }, style: "background-color: red; color: white; padding: 8px; border-radius: 4px;"%>
    </div>

    <%= link_to 'Back to Project', project_path(@project), class: "bg-gray-500 hover:bg-gray-700 text-white py-2 px-4 rounded transition duration-200" %>
  </div>
</div>