config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  resources :projects do
    member do
      post :invite # Route for inviting users
      get :accept_invite # Route for accepting invitations
    end
    resources :tasks
    resources :faqs
  end
  root "application#home"
  resources :notifications do
    member do
      post 'read'  # This creates a POST route for marking notifications as read
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
  after_save :create_notification
  belongs_to :project
  validates :name, presence: true
  enum status: { pending: 0, in_progress: 1, completed: 2 }

  private

  def create_notification
    self.project.users.each do |user|
      TaskCreatedNotifier.with(task: self, project: self.project).deliver_later(user)
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = @project.tasks
  end

  def new
    @task = @project.tasks.build
  end

  def create
    @task = @project.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path(@project), notice: 'Task was successfully deleted.'
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :status)
  end
end

app/views/tasks/_form.html.erb
<%= turbo_frame_tag id='task_form', target: '_top' do %>
  <%= form_with model: [project, task], local: true, class: "max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f| %>
    <div class="mb-4">
      <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <% if task.persisted? %>
      <div class="mb-4">
        <%= f.label :status, "Status", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.select :status, Task.statuses.keys.map { |status| [status.humanize, status] }, {}, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
    <% end %>

    <div class="flex justify-center items-center mt-6 space-x-4">
      <%= f.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-200 focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
<% end %>

app/views/tasks/_task.html.erb
<li class="flex items-center justify-between p-4 bg-white shadow-md rounded-lg">
  <div class="w-1/4">
    <p class="font-bold text-blue-500 hover:text-blue-700">
      <%= link_to truncate(task.name, length: 30), project_task_path(@project, task) %>
    </p>
  </div>

  <div class="w-1/2">
    <p class="text-gray-600">
      <%= truncate(task.description, length: 50) %>
    </p>
  </div>
  <div class="w-1/6 text-center">
    <span class="px-3 py-1 text-xs font-semibold rounded-full
      <%= case task.status
            when 'pending'
              'bg-yellow-200 text-yellow-800'
            when 'in_progress'
              'bg-blue-200 text-blue-800'
            when 'completed'
              'bg-green-200 text-green-800'
          end %>">
      <%= task.status.humanize %>
    </span>
  </div>

  <div class="w-1/6 text-right space-x-4">
    <%= link_to 'Edit', edit_project_task_path(@project, task), class: "text-blue-500 hover:text-blue-700" %>
    <%= link_to 'Delete', project_task_path(@project, task), data: { "turbo-method": :delete }, class: "text-red-500 hover:text-red-700" %>
  </div>
</li>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.append "tasks", @task %>
<%= turbo_stream.replace 'task_form', partial: 'form', locals: {project: @project, task: Task.new} %>

app/views/tasks/edit.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">Edit Task for <%= @project.name %></h1>
<div class="flex justify-center space-x-4 mb-4">
  <%= link_to 'Back to Tasks', project_tasks_path(@project), class: "bg-gray-500 text-white py-2 px-4 rounded transition duration-200 hover:bg-gray-600" %>
</div>

<%= turbo_frame_tag id='task_form' do %>
  <%= render 'form', task: @task, project: @project %>
<% end %>

app/views/tasks/index.html.erb
<div class="w-full flex flex-col items-center mb-1">
  <h1 class="text-2xl font-bold mb-4 text-center">Tasks for <%= @project.name %></h1>
</div>

<div class="flex justify-center space-x-4 mb-4">
  <%= link_to 'Back to Project', project_path(@project), class: "bg-gray-500 text-white py-2 px-4 rounded transition duration-200 hover:bg-gray-600" %>
</div>
<%= turbo_frame_tag id='task_form', src:new_project_task_path(@project) %>

<ul class="space-y-4 mb-4" id="tasks">
  <% @tasks.each do |task| %>
  <%= render 'task', task: task %>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h2 class="text-2xl font-bold mb-6 text-center">New Task for <%= @project.name %></h2>

<div class="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <%= turbo_frame_tag id='task_form' do %>
    <%= render 'form', task: @task, project: @project%>
  <% end %>
</div>

app/views/tasks/show.html.erb
<h1 class="text-3xl font-bold text-center mb-4">Task Details</h1>

<div class="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <div class="mb-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-2">Name:</h2>
    <p class="text-gray-700"><%= @task.name %></p>
  </div>

  <div class="mb-4">
    <h2 class="text-xl font-semibold text-gray-800 mb-2">Description:</h2>
    <p class="text-gray-700"><%= @task.description %></p>
  </div>

  <div class="flex justify-between items-center mt-6">
    <div class="flex space-x-4">
      <%= link_to 'Edit', edit_project_task_path(@project, @task), class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-200" %>
      <%= link_to 'Delete', project_task_path(@project, @task), data: { "turbo-method": :delete }, style: "background-color: red; color: white; padding: 8px; border-radius: 4px;" %>
    </div>

    <%= link_to 'Back to Project', project_path(@project), class: "bg-gray-500 hover:bg-gray-700 text-white py-2 px-4 rounded transition duration-200" %>
  </div>
</div>