config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  resources :projects do
    member do
      post :invite # Route for inviting users
      get :accept_invite # Route for accepting invitations
    end
    resources :tasks
    resources :faqs
  end
  root "application#home"
  resources :notifications do
    member do
      post 'read'  # This creates a POST route for marking notifications as read
    end
  end
end

app/models/project.rb
class Project < ApplicationRecord
  before_create :generate_invite_token

  belongs_to :user
  has_many :tasks, dependent: :destroy
  has_many :faqs, dependent: :destroy
  has_many :project_users, dependent: :destroy
  has_many :users, through: :project_users
  validates :name, presence: true
  validates :description, presence: true

  def send_invitation_email(user)
    token = SecureRandom.hex(10)
    update(token:)
    InvitationMailer.invite_user(user, self).deliver_now
  end

  private

  def generate_invite_token
    self.token = SecureRandom.hex(10)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = current_user.projects + current_user.invited_projects
  end

  def show; end

  def new
    @project = current_user.projects.build
  end

  def create
    @project = current_user.projects.build(project_params)
    respond_to do |format|
      if @project.save
        format.turbo_stream
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit; end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  def invite
    @project = current_user.projects.find(params[:id])
    invited_user = User.find_by(email: params[:email])
    if invited_user
      @project.send_invitation_email(invited_user)
      flash[:notice] = "Invitation sent to #{invited_user.email}."
    else
      flash[:alert] = 'User does not exist. Please create an account.'
    end
    redirect_to @project
  end

  def accept_invite
    if user_signed_in?
      @project = Project.find_by(token: params[:token])
      if @project
        @project.users << current_user unless @project.users.include?(current_user)
        @project.users << @project.user unless @project.users.include?(@project.user)
        AcceptInvitationNotifier.with(user: { name: current_user.name }, project: { name: @project.name }).deliver_later(@project.user)
        flash[:notice] = 'You have been added to the project.'
        redirect_to project_path(@project)
      else
        flash[:alert] = 'Invalid invitation.'
        redirect_to root_path
      end
    else
      flash[:alert] = 'You need to log in to accept the invitation.'
      redirect_to new_user_session_path
    end
  end

  private

  def set_project
    @project = Project.includes(:users).find(params[:id])
    unless @project.user == current_user || @project.users.include?(current_user)
      flash[:alert] = 'You do not have access to this project.'
      redirect_to projects_path
    end
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<%= turbo_frame_tag id='project_form', target: '_top' do %>
  <%= form_with model: project, class: "max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4" do |f| %>
      <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_area :description, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="flex items-center justify-between">
      <%= f.submit "Submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition duration-200 focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>
<% end %>

app/views/projects/_project.html.erb
<li class="flex justify-between items-center p-4 bg-white shadow-md rounded-lg">
  <div>
    <%= link_to project.name, project_path(project), class: "text-lg font-semibold text-blue-700 hover:underline" %>
  </div>
  <div class="space-x-2">
    <%= link_to 'Edit', edit_project_path(project), class: "text-blue-500 hover:text-blue-700" %>
    <%= link_to 'Delete', project_path(project), data: { "turbo-method": :delete }, class: "text-red-500 hover:text-red-700" %>
  </div>
</li>

app/views/projects/create.turbo_stream.erb
<%= turbo_stream.append "projects", @project %>
<%= turbo_stream.replace 'project_form', partial: 'form', locals: {project: Project.new} %>

app/views/projects/edit.html.erb
<h1 class="text-2xl font-bold mb-4 text-center">Edit Project</h1>
<div class="flex justify-center space-x-4 mb-4">
  <%= link_to 'Back to Projects', projects_path, class: "bg-gray-500 text-white py-2 px-4 rounded transition duration-200 hover:bg-gray-600" %>
</div>
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1 class="text-2xl font-bold mb-6 text-center">Projects</h1>

<%= turbo_frame_tag id='project_form', src:new_project_path %>
<ul class="space-y-4 mb-4" id="projects">
  <% @projects.each do |project| %>
    <%= render 'project', project: project%>
  <% end %>
</ul>

app/views/projects/new.html.erb
<%= turbo_frame_tag id='project_new' do %>
  <h2 class="text-2xl font-bold text-center mb-4">New Project</h2>
  <%= render "form", project: @project %>
<% end %>

app/views/projects/show.html.erb
<div class="max-w-md mx-auto bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
  <h1 class="text-3xl font-bold text-center mb-4"><%= @project.name %></h1>
  <p class="text-gray-700 text-base mb-6"><%= @project.description %></p>

  <div class="flex justify-between mb-4">
    <%= link_to 'Edit', edit_project_path(@project), class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-200" %>
    <%= link_to 'Back', projects_path, class: "bg-gray-500 hover:bg-gray-700 text-white py-2 px-4 rounded transition duration-200" %>
    <%= link_to 'View Tasks', project_tasks_path(@project), class: "bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded transition duration-200" %>
    <%= link_to 'View Faqs', project_faqs_path(@project), class: "bg-green-500 hover:bg-green-700 text-white py-2 px-4 rounded transition duration-200" %>
  </div>

  <div class="flex justify-center mb-4">
    <% if current_user == @project.user %>
      <button id="invite-button" class="bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-200">
        Invite User
      </button>
    <% end %>
  </div>

  <div id="email-input" class="hidden mb-4">
    <%= form_with url: invite_project_path(@project), method: :post, local: true do |f| %>
      <div class="max-w-md mx-auto mb-4">
        <%= f.label :email, "Invite User by Email", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= f.email_field :email, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
      </div>
      <div class="max-w-md mx-auto">
        <%= f.submit "Send Invite", class: "bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-200" %>
      </div>
    <% end %>
  </div>
</div>