config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'profile', to: 'profiles#show', as: :profile
  get 'profile/edit', to: 'profiles#edit', as: :edit_profile
  patch 'profile', to: 'profiles#update'

  resources :projects do
    member do
      post :invite # Route for inviting users
      get :accept_invite # Route for accepting invitations
    end
    resources :tasks
    resources :faqs
  end
  root "application#home"
  resources :notifications do
    member do
      post 'read'  # This creates a POST route for marking notifications as read
    end
  end
end

app/views/layouts/_errors.html.erb
<% flash.each do |type, message| %>
  <% flash_class = case type %>
    <% when "notice" then "bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded" %>
    <% when "alert" then "bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded" %>
  <% end %>
  <div class="<%= flash_class %>">
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/_nav.html.erb
<!-- app/views/layouts/application.html.erb -->
<nav class="bg-white shadow-md mb-2">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between h-16">
      <div class="flex">
        <div class="hidden md:flex items-center space-x-4">
          <%= link_to "Home", root_path, class: "text-lg font-bold text-blue-500" %>
          <% if user_signed_in? %>
            <%= link_to "Projects", projects_path, class: "text-lg font-bold text-blue-500" %>
          <% end %>
        </div>
      </div>
      <div class="hidden md:flex items-center relative">
        <% if user_signed_in? %>
          <div class="relative mr-4">
            <button class="relative text-gray-800 hover:text-blue-500 focus:outline-none mx-4" id="notifications-button">
              <i class="fas fa-bell"></i>
              <%= turbo_frame_tag "notification_count" do %>
                <% unread_count = current_user.notifications.unread.count %>
                <% if unread_count.positive? %>
                  <span id="notification-count" class="absolute top-0 right-0 inline-block w-5 h-5 bg-red-500 text-white rounded-full text-xs text-center">
                    <%= unread_count %>
                  </span>
                <% end %>
              <% end %>
            </button>
            <div class="absolute right-0 hidden mt-1 w-80 bg-white shadow-lg rounded-md z-10" id="notifications-dropdown">
              <div class="py-2" style="width: 300px;">
                <% if current_user.notifications.any? %>
                  <%= render 'layouts/notifications' %>
                <% else %>
                  <p class="px-4 py-2 text-sm text-gray-500">No new notifications.</p>
                <% end %>
              </div>
            </div>
          </div>

          <div class="relative">
            <button class="flex items-center text-gray-800 hover:text-blue-500 focus:outline-none" id="profile-button">
              <span>Profile</span>
              <svg class="ml-1 w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path>
              </svg>
            </button>
            <div class="absolute right-0 hidden mt-1 w-48 bg-white shadow-lg rounded-md z-10" id="profile-dropdown">
              <div class="py-1">
                <%= link_to 'Profile', profile_path, class: "block px-4 py-2 text-sm text-gray-800 hover:bg-gray-100" %>
                <%= link_to 'Logout', destroy_user_session_path, data: { "turbo-method": :delete }, class: "block px-4 py-2 text-sm text-gray-800 hover:bg-gray-100" %>
              </div>
            </div>
          </div>
        <% else %>
          <%= link_to 'Login', new_user_session_path, class: "text-gray-800 hover:text-blue-500" %>
          <%= link_to 'Sign Up', new_user_registration_path, class: "ml-4 text-gray-800 hover:text-blue-500" %>
        <% end %>
      </div>

      <div class="flex md:hidden">
        <button class="text-gray-800 hover:text-blue-500 focus:outline-none" id="mobile-menu-button">
          <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16m-7 6h7"></path>
          </svg>
        </button>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
<% current_user.notifications.each do |notification| %>
  <div class="<%= notification.read_at ? 'p-4 mb-2 bg-gray-50' : 'p-4 mb-2 bg-blue-100 shadow-lg' %> rounded-lg hover:shadow-xl transition-shadow duration-300">
    <%= link_to (if notification.params[:task].present? && notification.params[:project].present?
        "#{notification.params[:task][:name]} was created in #{notification.params[:project][:name]} project's tasks"
      elsif notification.params[:faq].present? && notification.params[:project].present?
        "#{notification.params[:faq][:question]} was created in #{notification.params[:project][:name]} project's FAQs"
      elsif notification.params[:user].present? && notification.params[:project].present?
        "#{notification.params[:user][:name]} accepted your invitation"
      else
        "Notification data is missing."
      end),
      read_notification_path(notification),
      method: :post,
      data: { turbo_method: :post },
      class: "text-gray-700 text-sm font-semibold" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/errors' %>
    <%= yield %>
    </body>

    </html>
    <script>
      const mobileMenuButton = document.getElementById('mobile-menu-button');
      const mobileMenu = document.getElementById('mobile-menu');

      mobileMenuButton.addEventListener('click', () => {
        mobileMenu.classList.toggle('hidden');
      });
    </script>